apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: assisted-installer
  name: assisted-service
spec:
  issuerRef:
    name: assisted-installer-ca
  dnsNames:
  - assisted-service.assisted-installer.svc
  - assisted-service.assisted-installer.svc.cluster.local
  secretName: assisted-service
